// 由 scripts/gen_seed.py 生成，与 database/seed.sql 同源，请勿手改
import type { Exercise, Plan, PlanDay } from './types';

export const SEED_EXERCISES: Exercise[] = [
  { id: 1, slug: "squat", name: "徒手深蹲", muscleGroup: "下肢", category: "力量", level: "入门",
    equipment: "无器械", caloriesPerMin: 8.0, measure: "reps",
    defaultReps: 15, defaultSeconds: null,
    gifUrl: "/gifs/squat.gif", steps: ["双脚与肩同宽，脚尖微外八，双臂前平举","臀部向后下方坐，膝盖跟随脚尖方向下蹲","大腿接近与地面平行后匀速站起，回到起始位"], tips: "膝盖不要内扣，下蹲时保持腰背自然挺直" },
  { id: 2, slug: "jack", name: "开合跳", muscleGroup: "全身", category: "有氧", level: "入门",
    equipment: "无器械", caloriesPerMin: 9.5, measure: "duration",
    defaultReps: null, defaultSeconds: 40,
    gifUrl: "/gifs/jack.gif", steps: ["双脚并拢站直，双手贴于身体两侧","轻跳同时双腿分开、双手在头顶击掌","再跳回并拢姿态，保持前脚掌着地、匀速呼吸"], tips: "用前脚掌缓冲落地，全程保持核心微收紧" },
  { id: 3, slug: "pushup", name: "俯卧撑", muscleGroup: "上肢", category: "力量", level: "初级",
    equipment: "无器械", caloriesPerMin: 8.5, measure: "reps",
    defaultReps: 10, defaultSeconds: null,
    gifUrl: "/gifs/pushup.gif", steps: ["双手略宽于肩撑地，身体从头到脚成一条直线","弯曲手臂下降身体，胸部接近地面","匀速推起回到起始位，手肘约成 45 度夹角"], tips: "力量不足可改为膝盖着地的跪姿俯卧撑" },
  { id: 4, slug: "plank", name: "平板支撑", muscleGroup: "核心", category: "稳定", level: "入门",
    equipment: "无器械", caloriesPerMin: 6.5, measure: "duration",
    defaultReps: null, defaultSeconds: 30,
    gifUrl: "/gifs/plank.gif", steps: ["前臂与脚尖撑地，手肘在肩膀正下方","收紧腹部与臀部，身体保持一条直线","均匀呼吸，保持到目标时长"], tips: "不要塌腰或撅臀，颈部自然延伸、眼看地面" },
  { id: 5, slug: "lunge", name: "交替弓步蹲", muscleGroup: "下肢", category: "力量", level: "初级",
    equipment: "无器械", caloriesPerMin: 8.0, measure: "reps",
    defaultReps: 12, defaultSeconds: null,
    gifUrl: "/gifs/lunge.gif", steps: ["站直，一脚向前迈出一大步","前脚全掌踩实，弯曲双膝下沉至前腿约 90 度","蹬前脚站回，左右交替进行"], tips: "前膝始终对准脚尖，不要超过脚尖太多" },
  { id: 6, slug: "crunch", name: "仰卧卷腹", muscleGroup: "核心", category: "力量", level: "入门",
    equipment: "无器械", caloriesPerMin: 6.0, measure: "reps",
    defaultReps: 15, defaultSeconds: null,
    gifUrl: "/gifs/crunch.gif", steps: ["仰卧屈膝，双脚踩地，双手轻扶耳侧","腹部发力卷起上背部，下背部贴地","在顶峰稍停后缓慢下落，不要用手抱头拉扯"], tips: "动作放慢，用腹肌而不是惯性完成" },
  { id: 7, slug: "knees", name: "原地高抬腿", muscleGroup: "全身", category: "有氧", level: "初级",
    equipment: "无器械", caloriesPerMin: 10.0, measure: "duration",
    defaultReps: null, defaultSeconds: 30,
    gifUrl: "/gifs/knees.gif", steps: ["站直，双臂弯曲约 90 度","左右交替快速抬膝至腰部高度","手臂配合自然摆动，前脚掌着地"], tips: "保持上身挺直，落地越轻越好" },
  { id: 8, slug: "stretch", name: "站立伸展", muscleGroup: "拉伸", category: "柔韧", level: "入门",
    equipment: "无器械", caloriesPerMin: 3.0, measure: "duration",
    defaultReps: null, defaultSeconds: 60,
    gifUrl: "/gifs/stretch.gif", steps: ["双脚交叉站稳，双手交叠举过头顶","吸气向上延展，呼气向一侧轻微侧弯","保持呼吸，换侧重复，结束后抖动手脚放松"], tips: "拉伸到有牵拉感即可，不要弹震、不要憋气" },
  { id: 9, slug: "bridge", name: "仰卧臀桥", muscleGroup: "下肢", category: "力量", level: "入门",
    equipment: "无器械", caloriesPerMin: 5.5, measure: "reps",
    defaultReps: 16, defaultSeconds: null,
    gifUrl: null, steps: ["仰卧屈膝，双脚靠近臀部踩地","臀部发力向上顶起，至肩髋膝成一条直线","顶峰夹紧臀部一秒，缓慢下落"], tips: "发力重点在臀部，不要过度顶腰" },
  { id: 10, slug: "climber", name: "登山跑", muscleGroup: "全身", category: "有氧", level: "中级",
    equipment: "无器械", caloriesPerMin: 10.5, measure: "duration",
    defaultReps: null, defaultSeconds: 30,
    gifUrl: null, steps: ["俯撑姿势，双手在肩下方、身体成直线","交替快速向胸前提膝，像原地跑步","保持髋部稳定不上下晃动"], tips: "核心始终收紧，速度以动作不变形为前提" },
  { id: 11, slug: "wallsit", name: "靠墙静蹲", muscleGroup: "下肢", category: "稳定", level: "初级",
    equipment: "无器械", caloriesPerMin: 6.0, measure: "duration",
    defaultReps: null, defaultSeconds: 30,
    gifUrl: null, steps: ["背靠墙站立，向前迈出双脚","沿墙下滑至大腿接近水平，小腿垂直地面","保持静蹲到目标时长，均匀呼吸"], tips: "膝盖不超过脚尖，大腿酸了就结束" },
  { id: 12, slug: "tap", name: "平板触肩", muscleGroup: "核心", category: "稳定", level: "中级",
    equipment: "无器械", caloriesPerMin: 7.5, measure: "reps",
    defaultReps: 14, defaultSeconds: null,
    gifUrl: null, steps: ["高位平板姿势，双手在肩下方撑地","保持躯干不晃，一手轻触对侧肩膀","左右交替进行，动作匀速"], tips: "髋部尽量不左右摇摆，核心收紧" }
];

export const SEED_PLANS: (Plan & { days: PlanDay[] })[] = [
  { id: 1, slug: "morning-wake", title: "晨间唤醒 7 天", description: "每天 8 分钟，用低强度动作唤醒身体，适合完全没有运动习惯的新手。", level: "入门", daysTotal: 7, minutesPerDay: 8, color: "#8FE3C1", tag: "起床 8 分钟", isPublished: true, days: [
    { id: 101, planId: 1, dayNumber: 1, title: "唤醒身体", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 1, sets: 1, reps: 15, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 60, restSeconds: 0}] },
    { id: 102, planId: 1, dayNumber: 2, title: "下肢激活", minutes: 5, items: [{exerciseId: 7, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 5, sets: 1, reps: 12, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 103, planId: 1, dayNumber: 3, title: "核心初体验", minutes: 5, items: [{exerciseId: 4, sets: 1, seconds: 20, restSeconds: 15}, {exerciseId: 6, sets: 1, reps: 12, restSeconds: 15}, {exerciseId: 2, sets: 1, seconds: 30, restSeconds: 0}] },
    { id: 104, planId: 1, dayNumber: 4, title: "臀腿唤醒", minutes: 5, items: [{exerciseId: 1, sets: 1, reps: 15, restSeconds: 15}, {exerciseId: 9, sets: 1, reps: 16, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 60, restSeconds: 0}] },
    { id: 105, planId: 1, dayNumber: 5, title: "心肺小跳", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 7, sets: 2, seconds: 20, restSeconds: 15}, {exerciseId: 4, sets: 1, seconds: 20, restSeconds: 0}] },
    { id: 106, planId: 1, dayNumber: 6, title: "上肢入门", minutes: 5, items: [{exerciseId: 3, sets: 1, reps: 8, restSeconds: 15}, {exerciseId: 5, sets: 1, reps: 12, restSeconds: 15}, {exerciseId: 6, sets: 1, reps: 12, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 40, restSeconds: 0}] },
    { id: 107, planId: 1, dayNumber: 7, title: "舒展恢复", minutes: 5, items: [{exerciseId: 8, sets: 2, seconds: 45, restSeconds: 15}, {exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 4, sets: 1, seconds: 25, restSeconds: 0}] } ] },
  { id: 2, slug: "full-burn", title: "全身燃脂 14 天", description: "有氧与力量交替编排，两周一轮，帮助建立稳定运动习惯、提升体能。", level: "初级", daysTotal: 14, minutesPerDay: 14, color: "#F26A55", tag: "每日 14 分钟", isPublished: true, days: [
    { id: 201, planId: 2, dayNumber: 1, title: "启动燃脂", minutes: 5, items: [{exerciseId: 2, sets: 2, seconds: 40, restSeconds: 15}, {exerciseId: 1, sets: 2, reps: 15, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 25, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 202, planId: 2, dayNumber: 2, title: "臀腿主导", minutes: 5, items: [{exerciseId: 7, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 5, sets: 2, reps: 12, restSeconds: 15}, {exerciseId: 9, sets: 2, reps: 16, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 203, planId: 2, dayNumber: 3, title: "核心循环", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 6, sets: 2, reps: 15, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 12, sets: 1, reps: 14, restSeconds: 10}] },
    { id: 204, planId: 2, dayNumber: 4, title: "上肢推力", minutes: 5, items: [{exerciseId: 7, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 3, sets: 2, reps: 10, restSeconds: 15}, {exerciseId: 1, sets: 2, reps: 15, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 205, planId: 2, dayNumber: 5, title: "跳跃心肺", minutes: 6, items: [{exerciseId: 2, sets: 3, seconds: 40, restSeconds: 15}, {exerciseId: 7, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 11, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 40, restSeconds: 0}] },
    { id: 206, planId: 2, dayNumber: 6, title: "下肢耐力", minutes: 5, items: [{exerciseId: 5, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 11, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 9, sets: 2, reps: 16, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 207, planId: 2, dayNumber: 7, title: "主动恢复", minutes: 5, items: [{exerciseId: 8, sets: 2, seconds: 60, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 2, sets: 1, seconds: 30, restSeconds: 0}] },
    { id: 208, planId: 2, dayNumber: 8, title: "全身循环 A", minutes: 5, items: [{exerciseId: 2, sets: 2, seconds: 40, restSeconds: 15}, {exerciseId: 1, sets: 2, reps: 16, restSeconds: 15}, {exerciseId: 6, sets: 2, reps: 15, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 30, restSeconds: 10}] },
    { id: 209, planId: 2, dayNumber: 9, title: "全身循环 B", minutes: 5, items: [{exerciseId: 7, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 5, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 3, sets: 2, reps: 10, restSeconds: 15}, {exerciseId: 12, sets: 2, reps: 14, restSeconds: 10}] },
    { id: 210, planId: 2, dayNumber: 10, title: "核心进阶", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 10, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 6, sets: 3, reps: 15, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 35, restSeconds: 10}] },
    { id: 211, planId: 2, dayNumber: 11, title: "臀腿爆发", minutes: 6, items: [{exerciseId: 1, sets: 3, reps: 15, restSeconds: 15}, {exerciseId: 9, sets: 3, reps: 16, restSeconds: 15}, {exerciseId: 11, sets: 2, seconds: 35, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 212, planId: 2, dayNumber: 12, title: "心肺挑战", minutes: 7, items: [{exerciseId: 2, sets: 3, seconds: 45, restSeconds: 15}, {exerciseId: 7, sets: 3, seconds: 30, restSeconds: 15}, {exerciseId: 10, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 40, restSeconds: 0}] },
    { id: 213, planId: 2, dayNumber: 13, title: "力量整合", minutes: 5, items: [{exerciseId: 3, sets: 2, reps: 12, restSeconds: 15}, {exerciseId: 5, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 12, sets: 2, reps: 16, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 35, restSeconds: 10}] },
    { id: 214, planId: 2, dayNumber: 14, title: "总结测试", minutes: 7, items: [{exerciseId: 2, sets: 2, seconds: 60, restSeconds: 15}, {exerciseId: 1, sets: 2, reps: 20, restSeconds: 15}, {exerciseId: 7, sets: 2, seconds: 40, restSeconds: 15}, {exerciseId: 8, sets: 2, seconds: 45, restSeconds: 0}] } ] },
  { id: 3, slug: "core-strong", title: "核心强化 21 天", description: "三周周期化核心训练，从静态稳定到动态抗疲劳，适合想强化腰腹的人。", level: "中级", daysTotal: 21, minutesPerDay: 12, color: "#C9B8FF", tag: "稳核心 护腰背", isPublished: true, days: [
    { id: 301, planId: 3, dayNumber: 1, title: "第 1 练 · 平板基础", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 25, restSeconds: 15}, {exerciseId: 6, sets: 2, reps: 12, restSeconds: 15}, {exerciseId: 12, sets: 1, reps: 12, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 302, planId: 3, dayNumber: 2, title: "第 2 练 · 核心燃动", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 10, sets: 1, seconds: 25, restSeconds: 15}, {exerciseId: 9, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 25, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 303, planId: 3, dayNumber: 3, title: "第 3 练 · 臀核协同", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 6, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 11, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 12, sets: 2, reps: 12, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 304, planId: 3, dayNumber: 4, title: "第 4 练 · 耐力递进", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 4, sets: 3, seconds: 20, restSeconds: 15}, {exerciseId: 10, sets: 2, seconds: 20, restSeconds: 15}, {exerciseId: 6, sets: 2, reps: 12, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 305, planId: 3, dayNumber: 5, title: "第 5 练 · 稳定挑战", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 12, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 9, sets: 2, reps: 16, restSeconds: 15}, {exerciseId: 4, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 306, planId: 3, dayNumber: 6, title: "第 6 练 · 腹部轰炸", minutes: 6, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 10, sets: 2, seconds: 25, restSeconds: 15}, {exerciseId: 6, sets: 3, reps: 12, restSeconds: 15}, {exerciseId: 11, sets: 2, seconds: 25, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 307, planId: 3, dayNumber: 7, title: "第 7 练 · 舒展巩固", minutes: 5, items: [{exerciseId: 2, sets: 1, seconds: 30, restSeconds: 15}, {exerciseId: 8, sets: 2, seconds: 50, restSeconds: 0}, {exerciseId: 4, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 308, planId: 3, dayNumber: 8, title: "第 8 练 · 平板基础", minutes: 7, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 4, sets: 3, seconds: 35, restSeconds: 15}, {exerciseId: 6, sets: 3, reps: 14, restSeconds: 15}, {exerciseId: 12, sets: 2, reps: 14, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 309, planId: 3, dayNumber: 9, title: "第 9 练 · 核心燃动", minutes: 7, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 10, sets: 2, seconds: 30, restSeconds: 15}, {exerciseId: 9, sets: 3, reps: 16, restSeconds: 15}, {exerciseId: 4, sets: 3, seconds: 35, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 310, planId: 3, dayNumber: 10, title: "第 10 练 · 臀核协同", minutes: 7, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 6, sets: 3, reps: 16, restSeconds: 15}, {exerciseId: 11, sets: 2, seconds: 40, restSeconds: 15}, {exerciseId: 12, sets: 3, reps: 14, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 311, planId: 3, dayNumber: 11, title: "第 11 练 · 耐力递进", minutes: 8, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 4, sets: 4, seconds: 30, restSeconds: 15}, {exerciseId: 10, sets: 3, seconds: 25, restSeconds: 15}, {exerciseId: 6, sets: 3, reps: 14, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 312, planId: 3, dayNumber: 12, title: "第 12 练 · 稳定挑战", minutes: 8, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 12, sets: 3, reps: 16, restSeconds: 15}, {exerciseId: 9, sets: 3, reps: 16, restSeconds: 15}, {exerciseId: 4, sets: 3, seconds: 40, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 313, planId: 3, dayNumber: 13, title: "第 13 练 · 腹部轰炸", minutes: 9, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 10, sets: 3, seconds: 30, restSeconds: 15}, {exerciseId: 6, sets: 4, reps: 14, restSeconds: 15}, {exerciseId: 11, sets: 3, seconds: 35, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 314, planId: 3, dayNumber: 14, title: "第 14 练 · 舒展巩固", minutes: 6, items: [{exerciseId: 2, sets: 1, seconds: 40, restSeconds: 15}, {exerciseId: 8, sets: 2, seconds: 50, restSeconds: 0}, {exerciseId: 4, sets: 3, seconds: 40, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 315, planId: 3, dayNumber: 15, title: "第 15 练 · 平板基础", minutes: 10, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 4, sets: 4, seconds: 45, restSeconds: 15}, {exerciseId: 6, sets: 4, reps: 16, restSeconds: 15}, {exerciseId: 12, sets: 3, reps: 16, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 316, planId: 3, dayNumber: 16, title: "第 16 练 · 核心燃动", minutes: 11, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 10, sets: 3, seconds: 35, restSeconds: 15}, {exerciseId: 9, sets: 4, reps: 18, restSeconds: 15}, {exerciseId: 4, sets: 4, seconds: 45, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 317, planId: 3, dayNumber: 17, title: "第 17 练 · 臀核协同", minutes: 10, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 6, sets: 4, reps: 18, restSeconds: 15}, {exerciseId: 11, sets: 3, seconds: 50, restSeconds: 15}, {exerciseId: 12, sets: 4, reps: 16, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 318, planId: 3, dayNumber: 18, title: "第 18 练 · 耐力递进", minutes: 12, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 4, sets: 5, seconds: 40, restSeconds: 15}, {exerciseId: 10, sets: 4, seconds: 30, restSeconds: 15}, {exerciseId: 6, sets: 4, reps: 16, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 319, planId: 3, dayNumber: 19, title: "第 19 练 · 稳定挑战", minutes: 11, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 12, sets: 4, reps: 18, restSeconds: 15}, {exerciseId: 9, sets: 4, reps: 16, restSeconds: 15}, {exerciseId: 4, sets: 4, seconds: 50, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 320, planId: 3, dayNumber: 20, title: "第 20 练 · 腹部轰炸", minutes: 12, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 10, sets: 4, seconds: 35, restSeconds: 15}, {exerciseId: 6, sets: 5, reps: 16, restSeconds: 15}, {exerciseId: 11, sets: 4, seconds: 45, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] },
    { id: 321, planId: 3, dayNumber: 21, title: "第 21 练 · 舒展巩固", minutes: 8, items: [{exerciseId: 2, sets: 1, seconds: 50, restSeconds: 15}, {exerciseId: 8, sets: 2, seconds: 50, restSeconds: 0}, {exerciseId: 4, sets: 4, seconds: 50, restSeconds: 15}, {exerciseId: 8, sets: 1, seconds: 45, restSeconds: 0}] } ] }
];
