-- ============================================================
-- NookFit 种子数据（由 scripts/gen_seed.py 生成，请勿手改）
-- 依赖 schema.sql 已创建的 7 张表
-- ============================================================
BEGIN;

TRUNCATE plan_days, plans, exercises RESTART IDENTITY CASCADE;

-- 1) 动作库 exercises
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (1,'squat','徒手深蹲','下肢','力量','入门','无器械',8.0,'reps',15,NULL,'/gifs/squat.gif',ARRAY['双脚与肩同宽，脚尖微外八，双臂前平举','臀部向后下方坐，膝盖跟随脚尖方向下蹲','大腿接近与地面平行后匀速站起，回到起始位'],'膝盖不要内扣，下蹲时保持腰背自然挺直');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (2,'jack','开合跳','全身','有氧','入门','无器械',9.5,'duration',NULL,40,'/gifs/jack.gif',ARRAY['双脚并拢站直，双手贴于身体两侧','轻跳同时双腿分开、双手在头顶击掌','再跳回并拢姿态，保持前脚掌着地、匀速呼吸'],'用前脚掌缓冲落地，全程保持核心微收紧');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (3,'pushup','俯卧撑','上肢','力量','初级','无器械',8.5,'reps',10,NULL,'/gifs/pushup.gif',ARRAY['双手略宽于肩撑地，身体从头到脚成一条直线','弯曲手臂下降身体，胸部接近地面','匀速推起回到起始位，手肘约成 45 度夹角'],'力量不足可改为膝盖着地的跪姿俯卧撑');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (4,'plank','平板支撑','核心','稳定','入门','无器械',6.5,'duration',NULL,30,'/gifs/plank.gif',ARRAY['前臂与脚尖撑地，手肘在肩膀正下方','收紧腹部与臀部，身体保持一条直线','均匀呼吸，保持到目标时长'],'不要塌腰或撅臀，颈部自然延伸、眼看地面');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (5,'lunge','交替弓步蹲','下肢','力量','初级','无器械',8.0,'reps',12,NULL,'/gifs/lunge.gif',ARRAY['站直，一脚向前迈出一大步','前脚全掌踩实，弯曲双膝下沉至前腿约 90 度','蹬前脚站回，左右交替进行'],'前膝始终对准脚尖，不要超过脚尖太多');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (6,'crunch','仰卧卷腹','核心','力量','入门','无器械',6.0,'reps',15,NULL,'/gifs/crunch.gif',ARRAY['仰卧屈膝，双脚踩地，双手轻扶耳侧','腹部发力卷起上背部，下背部贴地','在顶峰稍停后缓慢下落，不要用手抱头拉扯'],'动作放慢，用腹肌而不是惯性完成');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (7,'knees','原地高抬腿','全身','有氧','初级','无器械',10.0,'duration',NULL,30,'/gifs/knees.gif',ARRAY['站直，双臂弯曲约 90 度','左右交替快速抬膝至腰部高度','手臂配合自然摆动，前脚掌着地'],'保持上身挺直，落地越轻越好');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (8,'stretch','站立伸展','拉伸','柔韧','入门','无器械',3.0,'duration',NULL,60,'/gifs/stretch.gif',ARRAY['双脚交叉站稳，双手交叠举过头顶','吸气向上延展，呼气向一侧轻微侧弯','保持呼吸，换侧重复，结束后抖动手脚放松'],'拉伸到有牵拉感即可，不要弹震、不要憋气');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (9,'bridge','仰卧臀桥','下肢','力量','入门','无器械',5.5,'reps',16,NULL,'/gifs/bridge.gif',ARRAY['仰卧屈膝，双脚靠近臀部踩地','臀部发力向上顶起，至肩髋膝成一条直线','顶峰夹紧臀部一秒，缓慢下落'],'发力重点在臀部，不要过度顶腰');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (10,'climber','登山跑','全身','有氧','中级','无器械',10.5,'duration',NULL,30,'/gifs/climber.gif',ARRAY['俯撑姿势，双手在肩下方、身体成直线','交替快速向胸前提膝，像原地跑步','保持髋部稳定不上下晃动'],'核心始终收紧，速度以动作不变形为前提');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (11,'wallsit','靠墙静蹲','下肢','稳定','初级','无器械',6.0,'duration',NULL,30,'/gifs/wallsit.gif',ARRAY['背靠墙站立，向前迈出双脚','沿墙下滑至大腿接近水平，小腿垂直地面','保持静蹲到目标时长，均匀呼吸'],'膝盖不超过脚尖，大腿酸了就结束');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (12,'tap','平板触肩','核心','稳定','中级','无器械',7.5,'reps',14,NULL,'/gifs/tap.gif',ARRAY['高位平板姿势，双手在肩下方撑地','保持躯干不晃，一手轻触对侧肩膀','左右交替进行，动作匀速'],'髋部尽量不左右摇摆，核心收紧');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (13,'calf','站姿提踵','下肢','力量','入门','无器械',4.5,'reps',20,NULL,'/gifs/calf.gif',ARRAY['站直，双脚与髋同宽，双手前平举或扶墙保持平衡','脚跟抬到最高，前脚掌撑地停一秒','控制速度缓慢落下，脚跟轻触地面后重复'],'下落越慢越好，充分感受小腿后侧发力');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (14,'twist','俄罗斯转体','核心','力量','初级','无器械',7.0,'reps',16,NULL,'/gifs/twist.gif',ARRAY['坐于地面，双膝弯曲脚跟着地，上身略向后倾','双手在胸前合十，背部挺直、腹部收紧','上身左右转动，双手随转体摆到髋部两侧'],'转体来自胸椎，不要只甩手臂，全程稳住下盘');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (15,'birdog','鸟狗式','核心','稳定','初级','无器械',6.0,'reps',12,NULL,'/gifs/birdog.gif',ARRAY['四点跪姿，双手在肩下、双膝在髋下','伸出对侧手和脚，直到与背部成一条直线','顶峰停一秒后收回，换另一侧进行'],'保持骨盆水平不翻胯，眼睛看向地面保护颈椎');
INSERT INTO exercises(id,slug,name,muscle_group,category,level,equipment,calories_per_min,measure,default_reps,default_seconds,gif_url,steps,tips) VALUES (16,'superman','小燕飞','核心','力量','初级','无器械',5.5,'reps',12,NULL,'/gifs/superman.gif',ARRAY['俯卧，双臂向前伸直、双腿向后伸直','背部发力，手臂和双腿同时轻轻抬离地面','顶峰停一秒，缓慢落下回到放松位'],'颈部保持放松不要仰头，抬起高度不必勉强');

-- 2) 课程 plans / 3) 课程日 plan_days（items 为 jsonb 编排）
INSERT INTO plans(id,slug,title,description,level,days_total,minutes_per_day,color,tag,is_published) VALUES (1,'morning-wake','晨间唤醒 7 天','每天 8 分钟，用低强度动作唤醒身体，适合完全没有运动习惯的新手。','入门',7,8,'#8FE3C1','起床 8 分钟',true);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,1,'唤醒身体',5,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 1, "sets": 1, "reps": 15, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 60, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,2,'下肢激活',5,'[{"exercise_id": 7, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 5, "sets": 1, "reps": 12, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,3,'核心初体验',5,'[{"exercise_id": 4, "sets": 1, "seconds": 20, "rest_seconds": 15}, {"exercise_id": 6, "sets": 1, "reps": 12, "rest_seconds": 15}, {"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,4,'臀腿唤醒',5,'[{"exercise_id": 1, "sets": 1, "reps": 15, "rest_seconds": 15}, {"exercise_id": 9, "sets": 1, "reps": 16, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 60, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,5,'心肺小跳',5,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 7, "sets": 2, "seconds": 20, "rest_seconds": 15}, {"exercise_id": 4, "sets": 1, "seconds": 20, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,6,'上肢入门',5,'[{"exercise_id": 3, "sets": 1, "reps": 8, "rest_seconds": 15}, {"exercise_id": 5, "sets": 1, "reps": 12, "rest_seconds": 15}, {"exercise_id": 6, "sets": 1, "reps": 12, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 40, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (1,7,'舒展恢复',5,'[{"exercise_id": 8, "sets": 2, "seconds": 45, "rest_seconds": 15}, {"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 4, "sets": 1, "seconds": 25, "rest_seconds": 0}]'::jsonb);
INSERT INTO plans(id,slug,title,description,level,days_total,minutes_per_day,color,tag,is_published) VALUES (2,'full-burn','全身燃脂 14 天','有氧与力量交替编排，两周一轮，帮助建立稳定运动习惯、提升体能。','初级',14,14,'#F26A55','每日 14 分钟',true);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,1,'启动燃脂',5,'[{"exercise_id": 2, "sets": 2, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 1, "sets": 2, "reps": 15, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,2,'臀腿主导',5,'[{"exercise_id": 7, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 5, "sets": 2, "reps": 12, "rest_seconds": 15}, {"exercise_id": 9, "sets": 2, "reps": 16, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,3,'核心循环',5,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 6, "sets": 2, "reps": 15, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 12, "sets": 1, "reps": 14, "rest_seconds": 10}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,4,'上肢推力',5,'[{"exercise_id": 7, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 3, "sets": 2, "reps": 10, "rest_seconds": 15}, {"exercise_id": 1, "sets": 2, "reps": 15, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,5,'跳跃心肺',6,'[{"exercise_id": 2, "sets": 3, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 7, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 11, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 40, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,6,'下肢耐力',5,'[{"exercise_id": 5, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 11, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 9, "sets": 2, "reps": 16, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,7,'主动恢复',5,'[{"exercise_id": 8, "sets": 2, "seconds": 60, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,8,'全身循环 A',5,'[{"exercise_id": 2, "sets": 2, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 1, "sets": 2, "reps": 16, "rest_seconds": 15}, {"exercise_id": 6, "sets": 2, "reps": 15, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 30, "rest_seconds": 10}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,9,'全身循环 B',5,'[{"exercise_id": 7, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 5, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 3, "sets": 2, "reps": 10, "rest_seconds": 15}, {"exercise_id": 12, "sets": 2, "reps": 14, "rest_seconds": 10}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,10,'核心进阶',5,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 10, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 6, "sets": 3, "reps": 15, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 35, "rest_seconds": 10}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,11,'臀腿爆发',6,'[{"exercise_id": 1, "sets": 3, "reps": 15, "rest_seconds": 15}, {"exercise_id": 9, "sets": 3, "reps": 16, "rest_seconds": 15}, {"exercise_id": 11, "sets": 2, "seconds": 35, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,12,'心肺挑战',7,'[{"exercise_id": 2, "sets": 3, "seconds": 45, "rest_seconds": 15}, {"exercise_id": 7, "sets": 3, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 10, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 40, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,13,'力量整合',5,'[{"exercise_id": 3, "sets": 2, "reps": 12, "rest_seconds": 15}, {"exercise_id": 5, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 12, "sets": 2, "reps": 16, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 35, "rest_seconds": 10}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (2,14,'总结测试',7,'[{"exercise_id": 2, "sets": 2, "seconds": 60, "rest_seconds": 15}, {"exercise_id": 1, "sets": 2, "reps": 20, "rest_seconds": 15}, {"exercise_id": 7, "sets": 2, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 8, "sets": 2, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plans(id,slug,title,description,level,days_total,minutes_per_day,color,tag,is_published) VALUES (3,'core-strong','核心强化 21 天','三周周期化核心训练，从静态稳定到动态抗疲劳，适合想强化腰腹的人。','中级',21,12,'#C9B8FF','稳核心 护腰背',true);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,1,'第 1 练 · 平板基础',5,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 6, "sets": 2, "reps": 12, "rest_seconds": 15}, {"exercise_id": 12, "sets": 1, "reps": 12, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,2,'第 2 练 · 核心燃动',5,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 10, "sets": 1, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 9, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,3,'第 3 练 · 臀核协同',5,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 6, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 11, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 12, "sets": 2, "reps": 12, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,4,'第 4 练 · 耐力递进',5,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 4, "sets": 3, "seconds": 20, "rest_seconds": 15}, {"exercise_id": 10, "sets": 2, "seconds": 20, "rest_seconds": 15}, {"exercise_id": 6, "sets": 2, "reps": 12, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,5,'第 5 练 · 稳定挑战',5,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 12, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 9, "sets": 2, "reps": 16, "rest_seconds": 15}, {"exercise_id": 4, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,6,'第 6 练 · 腹部轰炸',6,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 10, "sets": 2, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 6, "sets": 3, "reps": 12, "rest_seconds": 15}, {"exercise_id": 11, "sets": 2, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,7,'第 7 练 · 舒展巩固',5,'[{"exercise_id": 2, "sets": 1, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 8, "sets": 2, "seconds": 50, "rest_seconds": 0}, {"exercise_id": 4, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,8,'第 8 练 · 平板基础',7,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 4, "sets": 3, "seconds": 35, "rest_seconds": 15}, {"exercise_id": 6, "sets": 3, "reps": 14, "rest_seconds": 15}, {"exercise_id": 12, "sets": 2, "reps": 14, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,9,'第 9 练 · 核心燃动',7,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 10, "sets": 2, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 9, "sets": 3, "reps": 16, "rest_seconds": 15}, {"exercise_id": 4, "sets": 3, "seconds": 35, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,10,'第 10 练 · 臀核协同',7,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 6, "sets": 3, "reps": 16, "rest_seconds": 15}, {"exercise_id": 11, "sets": 2, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 12, "sets": 3, "reps": 14, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,11,'第 11 练 · 耐力递进',8,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 4, "sets": 4, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 10, "sets": 3, "seconds": 25, "rest_seconds": 15}, {"exercise_id": 6, "sets": 3, "reps": 14, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,12,'第 12 练 · 稳定挑战',8,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 12, "sets": 3, "reps": 16, "rest_seconds": 15}, {"exercise_id": 9, "sets": 3, "reps": 16, "rest_seconds": 15}, {"exercise_id": 4, "sets": 3, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,13,'第 13 练 · 腹部轰炸',9,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 10, "sets": 3, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 6, "sets": 4, "reps": 14, "rest_seconds": 15}, {"exercise_id": 11, "sets": 3, "seconds": 35, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,14,'第 14 练 · 舒展巩固',6,'[{"exercise_id": 2, "sets": 1, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 8, "sets": 2, "seconds": 50, "rest_seconds": 0}, {"exercise_id": 4, "sets": 3, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,15,'第 15 练 · 平板基础',10,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 4, "sets": 4, "seconds": 45, "rest_seconds": 15}, {"exercise_id": 6, "sets": 4, "reps": 16, "rest_seconds": 15}, {"exercise_id": 12, "sets": 3, "reps": 16, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,16,'第 16 练 · 核心燃动',11,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 10, "sets": 3, "seconds": 35, "rest_seconds": 15}, {"exercise_id": 9, "sets": 4, "reps": 18, "rest_seconds": 15}, {"exercise_id": 4, "sets": 4, "seconds": 45, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,17,'第 17 练 · 臀核协同',10,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 6, "sets": 4, "reps": 18, "rest_seconds": 15}, {"exercise_id": 11, "sets": 3, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 12, "sets": 4, "reps": 16, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,18,'第 18 练 · 耐力递进',12,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 4, "sets": 5, "seconds": 40, "rest_seconds": 15}, {"exercise_id": 10, "sets": 4, "seconds": 30, "rest_seconds": 15}, {"exercise_id": 6, "sets": 4, "reps": 16, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,19,'第 19 练 · 稳定挑战',11,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 12, "sets": 4, "reps": 18, "rest_seconds": 15}, {"exercise_id": 9, "sets": 4, "reps": 16, "rest_seconds": 15}, {"exercise_id": 4, "sets": 4, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,20,'第 20 练 · 腹部轰炸',12,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 10, "sets": 4, "seconds": 35, "rest_seconds": 15}, {"exercise_id": 6, "sets": 5, "reps": 16, "rest_seconds": 15}, {"exercise_id": 11, "sets": 4, "seconds": 45, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);
INSERT INTO plan_days(plan_id,day_number,title,minutes,items) VALUES (3,21,'第 21 练 · 舒展巩固',8,'[{"exercise_id": 2, "sets": 1, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 8, "sets": 2, "seconds": 50, "rest_seconds": 0}, {"exercise_id": 4, "sets": 4, "seconds": 50, "rest_seconds": 15}, {"exercise_id": 8, "sets": 1, "seconds": 45, "rest_seconds": 0}]'::jsonb);

COMMIT;
